import { Locale, i18n } from "@/shared/lib/i18n";
import LayoutBase from "@/shared/ui/layout/ui/base.layout";
import LayoutPage from "@/shared/ui/layout/ui/page.layout";
import type { Metadata } from "next";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: Promise<{ lang: Locale }>;
}

export function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

const LayoutLang = async ({ children, params }: RootLayoutProps) => {
  const lang = (await params).lang;

  if (!i18n.locales.includes(lang as any)) {
    notFound();
  }
  return <LayoutBase lang={lang}>{children}</LayoutBase>;
};

export default LayoutLang;
