import { Locale } from "@/shared/lib/i18n/domain/type";
import { TeamItem } from "../domain/team.type";
import team_unit_photo from "../model/asset/team_unit.jpg";

export const TEAM_LIST: Record<Locale, Array<TeamItem>> = {
  ua: [
    {
      firstName: "Максим",
      lastName: "Журавльов",
      fatherName: "Сергійович",
      photo: team_unit_photo,
      position: "Голова адвокатського об'єднання, адвокат",
      specialization: "Кримінальне та адміністративне право",
      expirience: "12 років",
      regalies: "Керуючий партнер",
    },
    {
      firstName: "Олександр",
      lastName: "Клімов",
      fatherName: "Миколайович",
      photo: team_unit_photo,
      position: "Адвокат",
      specialization: "Кримінальне та адміністративне право",
      expirience: "19 років",
      regalies: "Керуючий партнер",
    },
    {
      firstName: "Інна",
      lastName: "Данилова",
      fatherName: "Олександрівна",
      photo: team_unit_photo,
      position: "Адвокат",
      specialization: "Кримінальне право",
      expirience: "22 років",
      regalies: "Старший партнер",
    },
    {
      firstName: "Севастьян",
      lastName: "Єрьоменко",
      fatherName: "Валеріанович",
      photo: team_unit_photo,
      position: "Адвокат",
      specialization: "Сімейні, трудові, майнові спори. Допомога військовим",
      expirience: "12 років",
      regalies: "Партнер",
    },
    {
      firstName: "Дар'я",
      lastName: "Гунченко",
      fatherName: "Ігорівна",
      photo: team_unit_photo,
      position: "Адвокат",
      specialization: "Цивільне та сімейне право",
      expirience: "5 років",
      regalies: "Партнер",
    },
    {
      firstName: "Ілля",
      lastName: "Терещенко",
      fatherName: "Ігорович",
      photo: team_unit_photo,
      position: "Адвокат",
      specialization: "Кримінальне право, захист бізнесу, антикорупційні кейси",
      expirience: "10 років",
      regalies: "Партнер об'єднання у м. Одеса",
    },
    {
      firstName: "Тетяна",
      lastName: "Головань",
      fatherName: "Георгіївна",
      photo: team_unit_photo,
      position: "Адвокат",
      specialization:
        "Податкові, антикорупційний комплаєнс, трудові, спадкові, сімейні спори",
      expirience: "23 років",
      regalies: "Кандидат юридичних наук, доцент, Партнер",
    },
    {
      firstName: "Єгор",
      lastName: "Тимошенко",
      fatherName: "Володимирович",
      photo: team_unit_photo,
      position: "Адвокат",
      specialization: "Адміністративні правопорушення, кримінальне право",
      expirience: "5 років",
      regalies: "Партнер",
    },
    {
      firstName: "Олександра",
      lastName: "Власенко",
      fatherName: "Олександрівна",
      photo: team_unit_photo,
      position: "Юрист",
      specialization: "Кримінальне та адміністративне право",
      expirience: "2 років",
      regalies: "",
    },
    {
      firstName: "Владислав",
      lastName: "Чуб",
      fatherName: "Євгенович",
      photo: team_unit_photo,
      position: "Юрист",
      specialization: "Кримінальне та адміністративне право",
      expirience: "2 років",
      regalies: "",
    },
  ],
  en: [
    {
      firstName: "Maxim",
      lastName: "Zhuravlyov",
      fatherName: "Sergeyovich",
      photo: team_unit_photo,
      position: "Head of legal association, lawyer",
      specialization: "Criminal and administrative law",
      expirience: "12 years",
      regalies: "Head partner",
    },
    {
      firstName: "Oleksandr",
      lastName: "Klimov",
      fatherName: "Mykolayovych",
      photo: team_unit_photo,
      position: "Lawyer",
      specialization: "Criminal and administrative law",
      expirience: "19 years",
      regalies: "Head partner",
    },
    {
      firstName: "Inna",
      lastName: "Danylova",
      fatherName: "Oleksandrivna",
      photo: team_unit_photo,
      position: "Lawyer",
      specialization: "Criminal law",
      expirience: "22 years",
      regalies: "Senior partner",
    },
    {
      firstName: "Sevastian",
      lastName: "Yeryomenko",
      fatherName: "Valerianovych",
      photo: team_unit_photo,
      position: "Lawyer",
      specialization:
        "Family, labor and property disputes. Assistance to military personnel",
      expirience: "12 years",
      regalies: "Partner",
    },
    {
      firstName: "Daria",
      lastName: "Gunchenko",
      fatherName: "Ihorivna",
      photo: team_unit_photo,
      position: "Lawyer",
      specialization: "Civil and family law",
      expirience: "5 years",
      regalies: "Partner",
    },
    {
      firstName: "Illia",
      lastName: "Tereshchenko",
      fatherName: "Ihorovych",
      photo: team_unit_photo,
      position: "Lawyer",
      specialization:
        "Criminal law, business protection, anti-corruption cases",
      expirience: "10 years",
      regalies: "Association partner in Odesa",
    },
    {
      firstName: "Tetiana",
      lastName: "Holovan",
      fatherName: "Heorhiyivna",
      photo: team_unit_photo,
      position: "Lawyer",
      specialization:
        "Tax disputes, anti-corruption compliance, labor, inheritance and family cases",
      expirience: "23 years",
      regalies: "PhD in Law, Associate Professor, Partner",
    },
    {
      firstName: "Yehor",
      lastName: "Tymoshenko",
      fatherName: "Volodymyrovych",
      photo: team_unit_photo,
      position: "Lawyer",
      specialization: "Administrative offenses, criminal law",
      expirience: "5 years",
      regalies: "Partner",
    },
    {
      firstName: "Oleksandra",
      lastName: "Vlasenko",
      fatherName: "Oleksandrivna",
      photo: team_unit_photo,
      position: "Legal counsel",
      specialization: "Criminal and administrative law",
      expirience: "2 years",
      regalies: "",
    },
    {
      firstName: "Vladyslav",
      lastName: "Chub",
      fatherName: "Yevhenovych",
      photo: team_unit_photo,
      position: "Legal counsel",
      specialization: "Criminal and administrative law",
      expirience: "2 years",
      regalies: "",
    },
  ],
};
