import { Locale } from "@/shared/lib/i18n/domain/type";
import { TeamItem } from "../domain/team.type";
import juravliov_maksim from "../model/asset/juravliov_maksim.jpg";
import klimov_oleksandr from "../model/asset/klimov_oleksandr.jpg";
import danilova_inna from "../model/asset/danilova_inna.jpg";
import eremenko_sevastian from "../model/asset/eremenko_sevastian.jpg";
import gunchenko_daria from "../model/asset/gunchenko_daria.jpg";
import terashenko_illa from "../model/asset/terashenko_illa.jpg";
import golovan_tetiana from "../model/asset/golovan_tetiana.jpg";
import timoshenko_egor from "../model/asset/timoshenko_egor.jpg";
import vaselenko_oleksandra from "../model/asset/vaselenko_oleksandra.jpg";
import chub_vladislav from "../model/asset/chub_vladislav.png";
// import from "../model/asset/";

export const TEAM_LIST: Record<Locale, Array<TeamItem>> = {
  ua: [
    {
      firstName: "Максим",
      lastName: "Журавльов",
      fatherName: "Сергійович",
      photo: juravliov_maksim,
      position: "Голова адвокатського об'єднання, адвокат",
      specialization: "Кримінальне та адміністративне право",
      expirience: "12 років",
      regalies: "Керуючий партнер",
    },
    {
      firstName: "Олександр",
      lastName: "Клімов",
      fatherName: "Миколайович",
      photo: klimov_oleksandr,
      position: "Адвокат",
      specialization: "Кримінальне та адміністративне право",
      expirience: "19 років",
      regalies: "Керуючий партнер",
    },
    {
      firstName: "Інна",
      lastName: "Данилова",
      fatherName: "Олександрівна",
      photo: danilova_inna,
      position: "Адвокат",
      specialization: "Кримінальне право",
      expirience: "22 років",
      regalies: "Старший партнер",
    },
    {
      firstName: "Севастьян",
      lastName: "Єрьоменко",
      fatherName: "Валеріанович",
      photo: eremenko_sevastian,
      position: "Адвокат",
      specialization: "Сімейні, трудові, майнові спори. Допомога військовим",
      expirience: "12 років",
      regalies: "Партнер",
    },
    {
      firstName: "Дар'я",
      lastName: "Гунченко",
      fatherName: "Ігорівна",
      photo: gunchenko_daria,
      position: "Адвокат",
      specialization: "Цивільне та сімейне право",
      expirience: "5 років",
      regalies: "Партнер",
    },
    {
      firstName: "Ілля",
      lastName: "Терещенко",
      fatherName: "Ігорович",
      photo: terashenko_illa,
      position: "Адвокат",
      specialization: "Кримінальне право, захист бізнесу, антикорупційні кейси",
      expirience: "10 років",
      regalies: "Партнер об'єднання у м. Одеса",
    },
    {
      firstName: "Тетяна",
      lastName: "Головань",
      fatherName: "Георгіївна",
      photo: golovan_tetiana,
      position: "Адвокат",
      specialization:
        "Податкові, антикорупційний комплаєнс, трудові, спадкові, сімейні спори",
      expirience: "23 років",
      regalies: "Кандидат юридичних наук, доцент, Партнер",
    },
    {
      firstName: "Єгор",
      lastName: "Тимошенко",
      fatherName: "Володимирович",
      photo: timoshenko_egor,
      position: "Адвокат",
      specialization: "Адміністративні правопорушення, кримінальне право",
      expirience: "5 років",
      regalies: "Партнер",
    },
    {
      firstName: "Олександра",
      lastName: "Власенко",
      fatherName: "Олександрівна",
      photo: vaselenko_oleksandra,
      position: "Юрист",
      specialization: "Кримінальне та адміністративне право",
      expirience: "2 років",
      regalies: "",
    },
    {
      firstName: "Владислав",
      lastName: "Чуб",
      fatherName: "Євгенович",
      photo: chub_vladislav,
      position: "Юрист",
      specialization: "Кримінальне та адміністративне право",
      expirience: "2 років",
      regalies: "",
    },
  ],
  en: [
    {
      firstName: "Maxim",
      lastName: "Zhuravlyov",
      fatherName: "Sergeyovich",
      photo: juravliov_maksim,
      position: "Head of legal association, lawyer",
      specialization: "Criminal and administrative law",
      expirience: "12 years",
      regalies: "Head partner",
    },
    {
      firstName: "Oleksandr",
      lastName: "Klimov",
      fatherName: "Mykolayovych",
      photo: klimov_oleksandr,
      position: "Lawyer",
      specialization: "Criminal and administrative law",
      expirience: "19 years",
      regalies: "Head partner",
    },
    {
      firstName: "Inna",
      lastName: "Danylova",
      fatherName: "Oleksandrivna",
      photo: danilova_inna,
      position: "Lawyer",
      specialization: "Criminal law",
      expirience: "22 years",
      regalies: "Senior partner",
    },
    {
      firstName: "Sevastian",
      lastName: "Yeryomenko",
      fatherName: "Valerianovych",
      photo: eremenko_sevastian,
      position: "Lawyer",
      specialization:
        "Family, labor and property disputes. Assistance to military personnel",
      expirience: "12 years",
      regalies: "Partner",
    },
    {
      firstName: "Daria",
      lastName: "Gunchenko",
      fatherName: "Ihorivna",
      photo: gunchenko_daria,
      position: "Lawyer",
      specialization: "Civil and family law",
      expirience: "5 years",
      regalies: "Partner",
    },
    {
      firstName: "Illia",
      lastName: "Tereshchenko",
      fatherName: "Ihorovych",
      photo: terashenko_illa,
      position: "Lawyer",
      specialization:
        "Criminal law, business protection, anti-corruption cases",
      expirience: "10 years",
      regalies: "Association partner in Odesa",
    },
    {
      firstName: "Tetiana",
      lastName: "Holovan",
      fatherName: "Heorhiyivna",
      photo: golovan_tetiana,
      position: "Lawyer",
      specialization:
        "Tax disputes, anti-corruption compliance, labor, inheritance and family cases",
      expirience: "23 years",
      regalies: "PhD in Law, Associate Professor, Partner",
    },
    {
      firstName: "Yehor",
      lastName: "Tymoshenko",
      fatherName: "Volodymyrovych",
      photo: timoshenko_egor,
      position: "Lawyer",
      specialization: "Administrative offenses, criminal law",
      expirience: "5 years",
      regalies: "Partner",
    },
    {
      firstName: "Oleksandra",
      lastName: "Vlasenko",
      fatherName: "Oleksandrivna",
      photo: vaselenko_oleksandra,
      position: "Legal counsel",
      specialization: "Criminal and administrative law",
      expirience: "2 years",
      regalies: "",
    },
    {
      firstName: "Vladyslav",
      lastName: "Chub",
      fatherName: "Yevhenovych",
      photo: chub_vladislav,
      position: "Legal counsel",
      specialization: "Criminal and administrative law",
      expirience: "2 years",
      regalies: "",
    },
  ],
};
