import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import clsx from "clsx";
import { ProvidersRoot } from "./_provider/providerRoot";
import { HeaderModule } from "@/widget/header";
import { sGlobal } from "@/shared/style";

const MontserratSans = Montserrat({
  variable: "--font-montserrat-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="ua"
      className={clsx(sGlobal.html, sGlobal.reset, sGlobal.color)}
    >
      <body className={`${MontserratSans.variable}`}>
        <HeaderModule />
        <ProvidersRoot>{children}</ProvidersRoot>
      </body>
    </html>
  );
}
