import { sGlobal } from "@/shared/style";
import { HeaderModule } from "@/widget/header";
import clsx from "clsx";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { routing } from "@/i18n/routing";
import { setRequestLocale } from "next-intl/server";

const MontserratSans = Montserrat({
  variable: "--font-montserrat-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

const LocalLayout = async ({ children, params }: RootLayoutProps) => {
  const locale = (await params).locale;
  setRequestLocale(locale);
  return (
    <html
      lang={locale}
      className={clsx(sGlobal.html, sGlobal.reset, sGlobal.color)}
    >
      <body className={`${MontserratSans.variable}`}>
        <HeaderModule />
        {children}
      </body>
    </html>
  );
};
export default LocalLayout;
