import { Locale } from "@/shared/lib/i18n/domain/type";
import { routing } from "@/shared/lib/i18n/routing";
import LayoutHTML from "@/shared/ui/layout/ui/html.layout";
import { HeaderModule } from "@/widget/header";
import type { Metadata } from "next";
import { setRequestLocale } from "next-intl/server";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: Promise<{ locale: Locale }>;
}

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

const LocalLayout = async ({ children, params }: RootLayoutProps) => {
  const locale = (await params).locale;

  if (!routing.locales.includes(locale as Locale)) {
    notFound();
  }

  setRequestLocale(locale);
  return (
    <LayoutHTML locale={locale}>
      <HeaderModule />
      {children}
    </LayoutHTML>
  );
};
export default LocalLayout;
